/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador;
import Modelo.Jugador;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class VentanaJuegos extends javax.swing.JInternalFrame {
    private Controlador controlador;
    private DefaultTableModel modelo;
    Thread jugador1;
    Thread jugador2;
    Thread jugador3;
    Thread jugador4;
    Thread mesa;
    Controlador c = new Controlador();
    int juego = 0;
    boolean jugando = true, mart = false;
    boolean gano1 = false, gano2 = false, gano3 = false, gano4 = false;
    int ju;
    int ja;

    /**
     * Creates new form VentanaJuegos
     */
    public VentanaJuegos(Controlador controlador) {
        initComponents();
        
        jugador1 = new Thread(new VentanaJuegos.jugador(1));
        jugador2 = new Thread(new VentanaJuegos.jugador(2));
        jugador3 = new Thread(new VentanaJuegos.jugador(3));
        jugador4 = new Thread(new VentanaJuegos.jugador(4));
        mesa = new Thread(new VentanaJuegos.mesas());
        jugador1.start();
        jugador2.start();
        jugador3.start();
        jugador4.start();
        mesa.start();
        this.controlador=controlador;
         modelo = new DefaultTableModel();
        modelo.addColumn("Dinero inicial");
        modelo.addColumn("Ganado");
        modelo.addColumn("perdido");
        
        this.jTable1.setModel(modelo);
       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        j1Cuenta = new javax.swing.JLabel();
        j1Num = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        j2Cuenta = new javax.swing.JLabel();
        j2Num = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bCuenta = new javax.swing.JLabel();
        bNum = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        j4Cuenta = new javax.swing.JLabel();
        j4Num = new javax.swing.JLabel();
        j3Cuenta = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        j3Num = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setText("Jugador 1");

        jLabel3.setText("Cuenta:");

        jLabel4.setText("Escogido:");

        j1Cuenta.setText("0");

        j1Num.setText("0");

        jLabel2.setText("Jugador 2");

        jLabel8.setText("Cuenta:");

        jLabel5.setText("Escogido:");

        j2Cuenta.setText("0");

        j2Num.setText("0");

        jLabel6.setText("Mesa");

        jLabel10.setText("Cuenta:");

        jLabel7.setText(" Escogido:");

        bCuenta.setText("0");

        bNum.setText("0");

        jLabel13.setText("Jugador 4");

        jLabel14.setText("Cuenta:");

        jLabel15.setText("Escogido:");

        j4Cuenta.setText("0");

        j4Num.setText("0");

        j3Cuenta.setText("0");

        jLabel9.setText("Jugador 3");

        jLabel11.setText("Cuenta:");

        jLabel12.setText("Escogido:");

        j3Num.setText("0");

        jButton2.setText("Jugar Par o Impar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        area.setColumns(20);
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        jButton3.setText("Jugar Martingala");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setText("Jugar Numero Concreto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jLabel16.setText("Id a buscar");

        jButton4.setText("Buscar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(232, 232, 232)
                                .addComponent(jButton2))
                            .addComponent(jButton1))
                        .addGap(87, 87, 87)
                        .addComponent(jButton3)
                        .addGap(29, 29, 29))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(33, 33, 33)
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(j3Cuenta)
                                    .addComponent(j3Num)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(j2Cuenta))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j2Num)))
                                .addGap(203, 203, 203)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(bCuenta))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bNum))
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(j1Cuenta))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j1Num)))))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(j4Cuenta)
                            .addComponent(j4Num))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(j1Cuenta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(j1Num))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(j2Cuenta)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(j2Num)
                                    .addComponent(jLabel10)
                                    .addComponent(bCuenta))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(bNum)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(j4Cuenta))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(j4Num))))
                        .addGap(55, 55, 55)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(j3Cuenta)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(j3Num)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        area.setText("");
        area.append("Jugando Par o Impar");
        c.apostar();
        juego = 2;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        area.setText("");
        area.append("Jugando Martingala\n");
        area.append("Jugador 1 aposto " + c.getVal1() + "\n");
        area.append("Jugador 2 aposto " + c.getVal2() + "\n");
        area.append("Jugador 3 aposto " + c.getVal3() + "\n");
        area.append("Jugador 4 aposto " + c.getVal4());
        c.apostarMartingala(gano1, gano2, gano3, gano4);
        juego = 1;
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        area.setText("");
        area.append("Jugando Numero Escogido");
        c.apostar();
        juego = 1;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         long id =Long.parseLong(txtId.getText());
         Jugador j =controlador.buscar(id);
         
       
        String[] info = new String[4];
        int x=controlador.getCuenta1();
        
        info[0]=x+"";
        info[1]=ju+"";
        info[2]=ja+"";
        
        modelo.addRow(info);
    }//GEN-LAST:event_jButton4ActionPerformed
    public class jugador implements Runnable {

        int jug;

        public jugador(int jugador) {
            this.jug = jugador;
        }

        @Override
        public void run() {
            while (true) {
                try {
                    if (juego != 0) {
                        int numero;
                        switch (jug) {
                            case 1:
                                j1Cuenta.setText(c.getCuenta1() + "");
                                
                                if (juego == 1) {
                                    numero = (int) (Math.random() * 36 + 1);
                                    j1Num.setText(numero + "");
                                 
                                } else if (juego == 2) {
                                    numero = (int) (Math.random() * 2 + 1);
                                    if (numero == 1) {
                                        j1Num.setText("Impar");
                                    } else {
                                        j1Num.setText("Par");
                                    }
                                }
                                System.out.println("jugo 1");
                                break;
                            case 2:
                                j2Cuenta.setText(c.getCuenta1() + "");
                                if (juego == 1) {
                                    numero = (int) (Math.random() * 36 + 1);
                                    j2Num.setText(numero + "");
                                } else if (juego == 2) {
                                    numero = (int) (Math.random() * 2 + 1);
                                    if (numero == 1) {
                                        j2Num.setText("Impar");
                                    } else {
                                        j2Num.setText("Par");
                                    }
                                }
                                System.out.println("jugo 2");
                                break;
                            case 3:
                                j3Cuenta.setText(c.getCuenta1() + "");
                                if (juego == 1) {
                                    numero = (int) (Math.random() * 36 + 1);
                                    j3Num.setText(numero + "");
                                } else if (juego == 2) {
                                    numero = (int) (Math.random() * 2 + 1);
                                    if (numero == 1) {
                                        j3Num.setText("Impar");
                                    } else {
                                        j3Num.setText("Par");
                                    }
                                }
                                System.out.println("jugo 3");
                                break;
                            case 4:
                                j4Cuenta.setText(c.getCuenta1() + "");
                                if (juego == 1) {
                                    numero = (int) (Math.random() * 36 + 1);
                                    j4Num.setText(numero + "");
                                } else if (juego == 2) {
                                    numero = (int) (Math.random() * 2 + 1);
                                    if (numero == 1) {
                                        j4Num.setText("Impar");
                                    } else {
                                        j4Num.setText("Par");
                                    }
                                }
                                System.out.println("jugo 4");
                                break;
                        }
                        jugando = false;
                    }
                    Thread.sleep(2000);
                } catch (InterruptedException ex) {

                }
            }
        }
    }

    public class mesas implements Runnable {

        @Override
        public void run() {
            while (true) {
                try {
                    if (!jugando) {
                        int numero;
                        System.out.println("Esperando");
                        bCuenta.setText(c.getCuentaB() + "");
                        switch (juego) {
                            case 1:
                                numero = (int) (Math.random() * 36 + 1);
                                bNum.setText(numero + "");
                                int res1 = Integer.parseInt(j1Num.getText());
                                int res2 = Integer.parseInt(j2Num.getText());
                                int res3 = Integer.parseInt(j3Num.getText());
                                int res4 = Integer.parseInt(j4Num.getText());
                                if (res1 == numero) {
                                    c.ganador1(360);
                                     j1Cuenta.setText(c.getCuenta1()+"");
                                     System.out.println(c.getCuenta1()+"");
                                    area.append("\nGano jugador 1");
                                    
                                    gano1 = true;
                                } else if (res2 == numero) {
                                    c.ganador2(360);
                                     j2Cuenta.setText(c.getCuenta2()+"");
                                    area.append("\nGano jugador 2");
                                    gano2 = true;
                                } else if (res3 == numero) {
                                    c.ganador3(360);
                                     j3Cuenta.setText(c.getCuenta3()+"");
                                    area.append("\nGano jugador 3");
                                    gano3 = true;
                                } else if (res4 == numero) {
                                    c.ganador4(360);
                                     j4Cuenta.setText(c.getCuenta4()+"");
                                    area.append("\nGano jugador 4");
                                    gano4 = true;
                                } else {
                                    area.append("\nGano la Mesa");
                                    gano1 = false;
                                    gano2 = false;
                                    gano3 = false;
                                    gano4 = false;
                                }
                                break;
                            case 2:
                                numero = (int) (Math.random() * 2 + 1);
                                if (numero == 1) {
                                    bNum.setText("Impar");
                                } else {
                                    bNum.setText("Par");
                                }
                                if (bNum.getText().equals(j1Num.getText())) {
                                    
                                    c.ganador1(20);
                                    j1Cuenta.setText(c.getCuenta1()+"");
                                     ju=c.getCuenta1()-1000;
                                     ja=1000/c.getCuenta1()*10;
                                    area.append("\nGano jugador 1");
                                  
                                }
                                if (bNum.getText().equals(j2Num.getText())) {
                                    c.ganador2(20);
                                     j2Cuenta.setText(c.getCuenta2()+"");
                                    area.append("\nGano jugador 2");
                                }
                                if (bNum.getText().equals(j3Num.getText())) {
                                    c.ganador3(20);
                                     j3Cuenta.setText(c.getCuenta3()+"");
                                    area.append("\nGano jugador 3");
                                }
                                if (bNum.getText().equals(j4Num.getText())) {
                                    c.ganador4(20);
                                     j4Cuenta.setText(c.getCuenta4()+"");
                                    area.append("\nGano jugador 4");
                                }
                                break;
                        }
                        area.append("\nFin del juego\n");
                        jugando = true;
                        juego = 0;
                    }
                    Thread.sleep(2000);
                } catch (InterruptedException ex) {

                }
            }
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JLabel bCuenta;
    private javax.swing.JLabel bNum;
    private javax.swing.JLabel j1Cuenta;
    private javax.swing.JLabel j1Num;
    private javax.swing.JLabel j2Cuenta;
    private javax.swing.JLabel j2Num;
    private javax.swing.JLabel j3Cuenta;
    private javax.swing.JLabel j3Num;
    private javax.swing.JLabel j4Cuenta;
    private javax.swing.JLabel j4Num;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
